[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "timetable_announcer"
authors = [{name = "John C. G. Sturdy", email = "jcg.sturdy@gmail.com"}]
description = "Python timetable slot handler"
readme = "README.md"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)"]
version = "0.0.3"
dependencies = [
]

[tool.pytest.ini_options]
pythonpath = [
  ".", "src",
]